### ISSUE TITLE
Crash on 1.19.4

### ISSUE THREAD

**Issue by Boy0000** [MisionThi/NBTtooltips#10]
```

Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:946)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.class_2588.<init>(java.lang.String, java.lang.Object[])'
	at net.mision_thi.nbttooltips.tooltips.TooltipChanger.Main(TooltipChanger.java:25)
	at net.minecraft.class_1799.handler$coc000$nbttooltips$injectEditTooltipmethod(class_1799.java:4161)
	at net.minecraft.class_1799.method_7950(class_1799.java:834)
	at net.minecraft.class_481.method_25409(class_481.java:754)
	at net.minecraft.class_465.method_2380(class_465.java:179)
	at net.minecraft.class_481.method_25394(class_481.java:743)
	at net.minecraft.class_437.method_47413(class_437.java:121)
	at net.minecraft.class_757.method_3192(class_757.java:937)
	... 6 more
```

**Comment by MisionThi** [comment]
I haven't updated to 1.19.4 yet, I will look at it when I got the time.
